// Generated by CoffeeScript 1.7.1
(function() {
  var addStyle, bind, bindGroups, displayResult, getIdSelector, getRandomColor, getResult, getText, getTextArray, highlight, putColor, resetHighlight;

  addStyle = function() {
    $("head").append("<style>.yellow{background-color: yellow;}</style>");
    $("head").append("<script src=\"http://code.jquery.com/jquery-1.11.0.min.js\"></script>");
    $("head").append("<script src=\"toto.js\"></script>");
  };

  bindGroups = function(groups) {
    _.each(groups, bind);
  };

  bind = function(elements) {
    var ids;
    ids = getIdSelector(elements);
    $(ids).hover(highlight, resetHighlight);
  };

  highlight = function() {
    $(this).addClass("yellow");
  };

  resetHighlight = function() {
    $(this).removeClass("yellow");
  };

  displayResult = function(groups) {
    _.each(groups, putColor);
  };

  putColor = function(elements) {
    var color, ids;
    ids = getIdSelector(elements);
    color = getRandomColor();
    $(ids).css("background-color", color);
  };

  getResult = function(groups) {
    return _.map(groups, getTextArray);
  };

  getTextArray = function(elements) {
    var ids;
    ids = getIdSelector(elements);
    return _.map($(ids), getText);
  };

  getText = function(element) {
    return $(element).text();
  };

  getIdSelector = function(element) {
    if (element.left === null && element.right === null) {
      return "#" + element.label;
    } else {
      return getIdSelector(element.left) + "," + getIdSelector(element.right);
    }
  };

  getRandomColor = function() {
    var color, i, letters;
    letters = "0123456789ABCDEF".split("");
    color = "#";
    i = 0;
    while (i < 6) {
      color += letters[Math.round(Math.random() * 15)];
      i++;
    }
    return color;
  };

}).call(this);
