(function(m){var window=this;var o4=function(){return(0,m.O)("feed-item-checkbox",p4)};var q4=function(a,b){if("FORM"==a.tagName)for(var c=a.elements,d=0;a=c[d];d++)q4(a,b);else!0==b&&a.blur(),a.disabled=b};var r4=function(a){(0,m.P)("yt-alert-content",s4).innerHTML=a;m.T.show(s4);m.T.hide(t4)};var u4=function(){var a=[],b=!0,c=o4();(0,m.y)(c,function(c){c.checked&&(a.push(c.value),b=!1)});(0,m.Fc)(v4,"video-ids",a.join(","));q4(v4,b);q4(w4,b);x4&&q4(x4,b);y4&&q4(y4,0==c.length)};
var z4=function(a,b,c,d){var e="",g={};"personal"==b?(e="/feed_ajax?action_load_personal_feed=1",g={feed_name:a}):"social"==b?(e="/feed_ajax?action_load_social_feed=1",g={feed_name:a}):"system"==b?(e="/feed_ajax?action_load_system_feed=1",g={feed_name:a}):"main"==b?e="/feed_ajax?action_load_main_feed=1":"user"==b?(e="/feed_ajax?action_load_user_feed=1",g={user_id:a}):"collection"==b&&(e="/feed_ajax?action_load_collection_feed=1",g={collection_id:a});c&&(g.filter_type=c);d&&(g.paging=d);(0,m.t)("FEED_DEBUG")&&
(g.debug=(0,m.t)("FEED_DEBUG"));return{url:e,ia:g}};var A4=function(a){r4(a);m.T.toggle((0,m.C)("watch-history-pause-container"),(0,m.C)("watch-history-resume-container"))};var B4=function(){var a=(0,m.O)("watched",p4).length;C4&&q4(C4,0==a)};var D4=function(a){if(E4){var b=(0,window.parseInt)((0,m.Qe)(E4).replace(F4,""),10);E4.innerHTML=b-a}u4();(0,m.cm)(G4,!1);(0,m.Tq)(p4)};
var H4=function(a){if(!(0,m.Cd)(a,"expanded")){var b=(0,m.C)("mep-container");null!=b&&((b=(0,m.P)("expanded",b))&&(0,m.Ad)(b,"expanded","collapsed"),(0,m.Ad)(a,"collapsed","expanded"))}};
var I4=function(a,b,c,d,e){c=z4(b,c,d,e);b=c.url;c=c.ia;var g=(0,m.P)("feed-load-more-container",a);(0,m.K)(g,"loading");(0,m.V)(b,{ia:c,format:"JSON",onSuccess:function(b,c){var d=(0,m.Qf)(c.feed_html);if(d){var e=(0,m.P)("last",a);e&&(0,m.M)(e,"last");(0,m.ve)(d,g);(0,m.Tq)(d);m.By.getInstance().Ed();(0,m.M)(g,"loading");c.paging?(0,m.Fc)(a,"paging",c.paging):m.T.hide(g);m.T.hide(J4)}else(0,m.M)(g,"loading")},onError:function(){(0,m.M)(g,"loading");m.T.show(J4)}})};
var daa=function(){r4((0,m.H)("HISTORY_FEED_CLEARED"));var a=o4();0!=a.length&&((0,m.Ve)(a[0],"UL").innerHTML="",u4())};var eaa=function(){A4((0,m.H)("HISTORY_FEED_RESUMED"))};var faa=function(){A4((0,m.H)("HISTORY_FEED_PAUSED"))};var K4=function(){m.T.hide(s4);m.T.show(t4)};var gaa=function(){var a=0;(0,m.y)(o4(),function(b){b.checked&&((0,m.ye)((0,m.Ve)(b,"LI")),a++)});D4(a)};
var haa=function(){r4((0,m.H)("WATCHED_VIDEOS_REMOVED"));var a=0;(0,m.y)((0,m.O)("watched",p4),function(b){(0,m.ye)((0,m.Ve)(b,"LI"));a++});D4(a);B4()};var L4=function(a){(0,m.y)(o4(),function(b){(0,m.cm)(b,a)});u4()};var iaa=function(a){a=(0,m.Q)(a.currentTarget,"music-promo-item");var b=(0,m.Cd)(a,"collapsed"),c=(0,m.Cd)(a,"subscribed");b&&c&&H4(a)};
var jaa=function(a){var b=(0,m.Q)(a.currentTarget,"music-promo-item");a=(0,m.F)(b,"external-id");var c=(0,m.Cd)(b,"last")?1:0,d=M4.shift();(0,m.V)("/engagement_wizard_ajax",{method:"POST",ia:{action_dismiss_item_mep2:"1"},ga:{session_token:(0,m.Yc)("engagement_wizard_ajax"),dismissed_channel:a,next_channel:d,is_last_item:c,column_name:(0,m.t)("MEP_COLUMN_NAME")},Aa:function(a,c){(0,m.Zu)(b,{duration:0.5,Aa:function(){var a=c.html_content;m.T.hide(b);if(a){b.innerHTML=a;var d=b.parentNode;if(d&&11!=
d.nodeType)if(b.removeNode)b.removeNode(!1);else{for(;a=b.firstChild;)d.insertBefore(a,b);(0,m.ye)(b)}(0,m.Yu)(b,0,1,{duration:0.5})}if(0==M4.length)for(a=(0,m.O)("mep2-dismiss-button"),d=0;d<a.length;d++)m.T.setVisible(a[d],!1)}})}})};var kaa=function(a){var b=(0,m.C)("mep-container");if(null!=b)for(var b=(0,m.O)("yt-uix-subscription-button",b),c=0;c<b.length;c++)if((0,m.F)(b[c],"channel-external-id")==a){a=(0,m.Q)(b[c],"music-promo-item");H4(a);(0,m.K)(a,"subscribed");break}};
var laa=function(a){a=a.getServiceInfo();for(var b in a){var c=(0,m.C)(b+"-connected");if(c){var d=a[b],e=(0,m.C)(b+"-not-connected"),g=(0,m.C)(b+"-display-name"),h=d.is_connected;m.T.Fb(c,h);m.T.Fb(e,!h);(0,m.Ne)(g,d.connected_as||"")}}};var N4=function(a){a=(0,m.Q)(a,"feed-container");var b=(0,m.Q)(a,"individual-feed"),c=(0,m.F)(b,"feed-name")||null,b=(0,m.F)(b,"feed-type")||null,d=(0,m.F)(a,"filter-type")||null,e=(0,m.F)(a,"paging")||null;I4(a,c,b,d,e)};
var maa=function(){(0,m.V)("/feed_change_ajax",{method:"POST",ia:{action_clear_history:1},ga:{session_token:(0,m.Yc)("feed_change_ajax")},onSuccess:daa,onError:K4})};var naa=function(){(0,m.V)("/feed_change_ajax",{method:"POST",ia:{action_resume_history:1},ga:{session_token:(0,m.Yc)("feed_change_ajax")},onSuccess:eaa,onError:K4})};var oaa=function(){(0,m.V)("/feed_change_ajax",{method:"POST",ia:{action_pause_history:1},ga:{session_token:(0,m.Yc)("feed_change_ajax")},onSuccess:faa,onError:K4})};
var paa=function(){(0,m.V)("/feed_change_ajax",{method:"POST",ia:{action_clear_watched_from_watch_later:1},ga:{session_token:(0,m.Yc)("feed_change_ajax")},onSuccess:haa,onError:K4})};
var qaa=function(){var a=(0,m.F)(v4,"video-ids"),b={};switch(O4){case "history":b.action_remove_history_entries=1;break;case "watch_later":b.action_remove_watch_later_entries=1;break;case "favorites":b.action_remove_favorites_entries=1;break;default:throw Error("Unsupported feed name: "+O4);}(0,m.V)("/feed_change_ajax",{method:"POST",ia:b,ga:{session_token:(0,m.Yc)("feed_change_ajax"),video_ids:a},onSuccess:gaa,onError:K4})};var raa=function(){u4()};
var saa=function(a){a="false"!=(0,m.F)(a.currentTarget,"enabled");(0,m.cm)(G4,a);L4(a)};var taa=function(a){L4(a.currentTarget.checked)};var P4=function(a){a=a||window.event;a.returnValue=!1;a.preventDefault&&a.preventDefault()};var uaa=function(a){P4(a);a=(0,m.Q)(a.currentTarget,"feed-item-collapsed-container");(0,m.Bd)(a,"expanded","collapsed");(0,m.Kn)()};var vaa=function(a){P4(a);a=(0,m.Q)(a.currentTarget,"feed-item-collapsed-container");(0,m.Bd)(a,"collapsed","expanded");(0,m.Kn)()};
var waa=function(a){N4(a.currentTarget)};var xaa=function(a){(0,m.V)("/addto_ajax?action_delete_from_playlist=1",{format:"XML",method:"POST",ga:{video_ids:a.vb,full_list_id:a.dl||"",session_token:(0,m.Yc)("addto_ajax")},W:a.W,onError:a.onError,onSuccess:a.onSuccess})};
var Q4=function(a,b){this.b=a;this.F=b;this.j=null;this.k=(0,m.C)("page");this.j=(0,m.R)((0,m.C)("premium-yva-close"),"click",(0,m.q)(this.Ps,this));var c=this.b;m.oh.getInstance().get("HIDDEN_MASTHEAD_ID")==c||(0,m.K)(this.k,"masthead-ad-expanded");this.D=(0,m.R)(window,"message",(0,m.q)(this.HB,this))};var R4=function(a){var b=m.oh.getInstance();b.set("HIDDEN_MASTHEAD_ID",a);b.save()};
var yaa=function(){var a=(0,m.t)("PYV_IFRAME_CONTENT"),b=(0,m.C)((0,m.t)("PYV_IFRAME_ID"));b&&(b=b.contentDocument||b.contentWindow.document,b.open(),b.write("<!DOCTYPE html><html><head></head><body>"+a+"</body></html>"),m.Ud||b.close())};var zaa=function(){var a=(0,m.C)("destination-moments-promo");if(a){var b=(0,m.F)(a,"column-name")||"";S4=(0,m.fg)(a,"click",(0,m.D)(Aaa,b),"destination-moments-promo-close")}};var Aaa=function(a){m.T.hide((0,m.C)("destination-moments-promo"));(new m.Cy(a)).write("write_reject")};
var Baa=function(){var a=(0,m.C)("i18n-local-languages-feed-promo");if(a){var b=(0,m.F)(a,"column-name");if(b){var c={gl:(0,m.F)(a,"promo-gl")},c=(0,m.vf)(c);(0,m.Bf)("i18n-promo-show",c,void 0);c=(0,m.D)(Caa,b);b=(0,m.D)(Daa,b);T4.push((0,m.fg)(null,"click",c,"i18n-local-languages-feed-promo-language-option"),(0,m.fg)(a,"click",b,"i18n-local-languages-feed-promo-close"))}}};
var Caa=function(a,b){function c(){var a=window.document.forms["i18n-local-languages-feed-promo-form"];a.hl.value=d;a.submit()}var d=(0,m.F)(b.target,"lang-code"),e=(0,m.C)("i18n-local-languages-feed-promo"),g=(0,m.F)(e,"promo-gl"),e=(0,m.F)(e,"current-lang");(0,m.Af)("i18n-promo-select",(0,m.vf)({gl:g,lang:d,current:e}));(new m.Cy(a)).write("write_accept",{onSuccess:c,onError:c})};var Daa=function(a){(0,m.S)(T4);T4=[];(new m.Cy(a)).write("write_dismiss")};
var Eaa=function(){var a=(0,m.C)("music-onboarding-promo");if(a){var b=(0,m.F)(a,"column-name")||"";U4=(0,m.fg)(a,"click",(0,m.D)(Faa,b),"music-onboarding-promo-close")}};var Faa=function(a){m.T.hide((0,m.Q)((0,m.C)("music-onboarding-promo"),"feed-item-container"));(new m.Cy(a)).write("write_reject")};var Gaa=function(){(0,m.S)(V4);(0,m.Ka)(W4);(0,m.y)(X4,function(a){(0,m.w)(a)})};var Haa=function(a){a.preventDefault();a=(0,m.Q)(a.currentTarget,"branded-page-related-channels-item");Y4(a,!0)};
var Z4=function(a){(0,m.Zu)(a,{duration:0.3,Aa:function(){(0,m.ye)(a)}})};var Iaa=function(a){var b=(0,m.O)("branded-page-related-channels-item"),c=(0,m.Wb)(b,function(b){return(0,m.F)(b,"external-id")==a});c&&X4.push((0,m.u)(function(){Y4(c,!1)},2E3))};
var Y4=function(a,b){var c=window.document.getElementById("channels_you_may_know"),c=c&&(0,m.Me)(c,a),d=!!(0,m.P)("branded-page-related-channels-featured-badge",a),e=(0,m.F)(a,"external-id"),g=(0,m.Ve)(a,"ul"),g=(0,m.O)("branded-page-related-channels-item",g),g=(0,m.Mb)(g,function(a){return(0,m.F)(a,"external-id")}),h={};d&&(h.featured=1);c&&(h.channels_you_may_know=1);(0,m.V)("/guide_ajax?action_reload_channel=1",{method:"POST",ia:h,ga:{session_token:(0,m.Yc)("guide_ajax"),dismissed_id:e,shown_ids:g.join(),
dismiss_old_channel:b},onSuccess:function(b,c){var d=c.new_suggested_html;d?(d=(0,m.Qf)(d),(0,m.ze)(d,a),(0,m.Tq)(d),(0,m.Yu)(d,0,1,{duration:0.3})):Z4(a)},onError:function(){Z4(a)}})};var Jaa=function(){var a=(0,m.C)("user-interests-promo");if(a){var b=(0,m.F)(a,"external-id")||"";$4.push((0,m.fg)(a,"click",(0,m.D)(Kaa,b),"user-interests-promo-close"));$4.push((0,m.fg)(a,"click",(0,m.D)(Laa,b),"user-interests-promo-yes"));$4.push((0,m.fg)(a,"click",(0,m.D)(Maa,b),"user-interests-promo-no"))}};
var Kaa=function(a){m.T.hide("user-interests-promo");a5&&b5(a,"dismiss")};var Laa=function(a){m.T.hide("user-interests-promo-question");m.T.show("user-interests-promo-details");a5=!1;b5(a,"yes");m.By.getInstance().Ed();(a=(0,m.C)("user-interests-promo-shelf"))&&(0,m.Tq)(a)};var Maa=function(a){m.T.hide("user-interests-promo");b5(a,"no")};
var b5=function(a,b){var c=(0,m.Yc)("user_interests_promo_ajax_token"),d={external_channel_id:a};d["action_"+b]=1;(0,m.V)("/user_interests_promo_ajax",{method:"POST",ia:d,ga:{session_token:c}})};
var Naa=function(){"DELAYED_EMBEDED"in m.ua&&(0,m.y)((0,m.t)("DELAYED_EMBEDED"),function(a){(0,m.Dh)(a.container,a.swf_config)});"MASTHEAD_ENCRYPTED_ID"in m.ua&&(window.masthead=new Q4((0,m.t)("MASTHEAD_ENCRYPTED_ID"),(0,m.t)("MASTHEAD_IS_BRANDED")));"PYV_IFRAME_ID"in m.ua&&yaa();zaa();Baa();Eaa();Jaa();V4=(0,m.fg)(window.document.body,"click",Haa,"branded-page-related-channels-item-close");W4.push((0,m.x)("subscription-subscribe-loaded",Iaa));(0,m.Ry)();var a=(0,m.C)("destination-moments-promo");
a&&(a={"impression-count":(0,m.F)(a,"impression-count")||""},(0,m.Af)("destination-moments-promo-show",(0,m.vf)(a)))};var c5=function(a){this.F=a;this.ja=(0,m.C)("shared-addto-menu");this.H=(0,m.F)(this.F,"feature")||"";if(a=(0,m.F)(a,"deferred-save"))this.k="true"==a.toLowerCase();this.D=(0,m.F)(this.F,"video-ids")||"";(0,m.Cc)(d5)||(d5=(0,m.vd)(this.ja,"lightweight-panel"));(a=(0,m.P)("sign-in",this.ja))?(0,m.R)(a,"click",(0,m.q)(this.aG,this)):this.Ef()};
var e5=function(a){var b=Oaa(a);(0,m.A)("addto-menu-changed",{videoIds:a.D,selectedPlaylists:b})};var Paa=function(a){var b=[];(0,m.ad)(b,(0,m.O)("playlist-name",a.b.list));(0,m.y)(b,function(a){(0,m.Nf)(a)&&(a=(0,m.Q)(a,"addto-playlist-item"),a.title=(0,m.F)(a,"possible-tooltip"))})};
var Qaa=function(a){var b=[],c=[];a=(0,m.O)("addto-playlist-item",a.ja);(0,m.y)(a,function(a){(0,m.vd)(a,"to-be-removed")&&b.push((0,m.F)(a,"full-list-id"));(0,m.vd)(a,"to-be-added")&&c.push((0,m.F)(a,"full-list-id"))});return{HI:b,GI:c}};var Raa=function(a,b){var c=(0,m.O)("addto-playlist-item",a.ja);(0,m.y)(c,function(a){var c=(0,m.F)(a,"full-list-id");-1<(0,m.la)(b.HI,c)?(0,m.I)(a,"to-be-removed"):-1<(0,m.la)(b.GI,c)&&(0,m.I)(a,"to-be-added")})};
var Oaa=function(a){var b=(0,m.O)("contains-selected-videos",a.ja),c=(0,m.O)("to-be-added",a.ja),d=(0,m.O)("to-be-removed",a.ja),e=[];b&&(0,m.y)(b,function(a){-1<(0,m.la)(d,a)||e.push({id:(0,m.F)(a,"item-id"),name:(0,m.F)(a,"item-name")})});c&&(0,m.y)(c,function(a){e.push({id:(0,m.F)(a,"item-id"),name:(0,m.F)(a,"item-name")})});return e};var Saa=function(a,b){xaa({vb:a.D,dl:b,onSuccess:function(){this.Ef()},W:a});(0,m.Ec)(a.ja,"video-ids")};
var Taa=function(a,b){if(b){var c=m.ie?"webkitTransitionEnd":m.qg?"oTransitionEnd":m.pg?"transitionend":m.Ud&&(0,m.Qd)(10)?"MSTransitionEnd":null;c?(0,m.cg)(a,c,function(){b()}):(0,m.u)(b,0)}};
var f5=function(a,b,c){c=c?"slide":"fade";var d=["fade","slide"];(0,m.Il)(a.j,d);(0,m.I)(a.j,c);(0,m.Il)(b,d);(0,m.I)(b,c);d5&&b==a.b.list&&(0,m.I)(a.ja,"lightweight-panel");(0,m.vd)(b,"dismissed-panel")?((0,m.J)(b,"dismissed-panel"),(0,m.J)(a.j,"active-panel")):(c=a.j,(0,m.vd)(c,"active-panel")&&((0,m.J)(c,"active-panel"),(0,m.I)(c,"dismissed-panel")));(0,m.I)(b,"active-panel");a.j=b};
var Uaa=function(a){var b=a.J=(0,m.P)("addto-create-playlist",a.b.Ze);(0,m.R)(b,"keydown",(0,m.q)(a.Ap,a));(0,m.R)(b,"paste",(0,m.q)(a.Ap,a));Taa(a.b.Ze,function(){b.focus()});var c=(0,m.P)("addto-create-cancel-button",a.b.Ze);(0,m.R)(c,"click",(0,m.q)(function(){f5(this,this.b.list,!0)},a));c=(0,m.P)("create-playlist-button",a.b.Ze);(0,m.R)(c,"click",(0,m.q)(a.sF,a));a.K=(0,m.P)("privacy-form",a.b.Ze);(0,m.fg)(a.K,"click",(0,m.q)(a.Ap,a),"playlist-privacy-option");a.M=(0,m.P)("addto-create-playlist-label",
a.b.Ze);a.U=(0,m.P)("create-playlist-button",a.b.Ze)};var g5=function(a,b,c,d){(0,m.Cs)({vb:a.k?"":a.D,dl:c,Cp:a.G?b:null,privacy:d,PF:a.H,onSuccess:a.ZF,onError:a.YF,W:a});a.k||(0,m.Ec)(a.ja,"video-ids")};var Vaa=function(a,b){var c=(0,m.O)("addto-playlist-item",a.ja);return(0,m.Wb)(c,function(a){return(0,m.F)(a,"full-list-id")==b})};
var h5=function(){this.ja=(0,m.C)("tag-editing-menu");this.Bi=(0,m.P)("yt-combobox-menu-content",this.ja);this.b=(0,m.P)("yt-combobox-search-input",this.ja);this.j=(0,m.P)("tag-resource-container");this.Pc()};var i5=function(a){a.xf?a.Ip=!0:a.Ef()};
var Waa=function(a,b){a.k=(0,m.P)("add-new-tag");a.Hv=(0,m.P)("apply-tag-changes");if(b){var c=(0,m.ae)("input","tag-checkbox",void 0);(0,m.y)(c,function(a){var c=b[a.value];(0,m.Fc)(a,"initial-tag-membership",c);(0,m.Fc)(a,"current-tag-membership",c);"ALL"==c?a.checked=!0:"SOME"==c&&(0,m.gm)(a,!0)},a)}j5(a)};var j5=function(a){for(var b=(0,m.ae)("input","tag-checkbox",void 0),c=!1,d=0;d<b.length;d++)if(!Xaa(b[d])){c=!0;break}c?(0,m.wd)(a.ja,"show-new","show-apply"):(0,m.wd)(a.ja,"show-apply","show-new")};
var Xaa=function(a){switch((0,m.F)(a,"initial-tag-membership")){case "SOME":if(a.Jm)return!0;break;case "NONE":if(!a.checked)return!0;break;case "ALL":if(a.checked)return!0}return!1};var k5=function(a,b){if(b){var c=b.error;if(c){var d=(0,m.P)("error-small-template",a.ja),d=(0,m.Kf)(d);l5(a,"yt-alert-error",c,d,8E3)}}};var m5=function(a,b){if(b){var c=b.success_msg;if(c){var d=(0,m.P)("success-small-template",a.ja),d=(0,m.Kf)(d);l5(a,"yt-alert-success",c,d,3E3)}}};
var l5=function(a,b,c,d,e){var g=(0,m.P)("tag-menu-notifications",a.ja);(0,m.kq)(b,c,d,g);(0,m.u)((0,m.q)(function(){(new m.qu(d,750)).Oa()},a),e)};var n5=function(a){a=(0,m.ae)("input",a,void 0);for(var b=[],c=[],d=0;d<a.length;d++){var e=a[d];e.Jm||(e.checked?b.push(e.value):c.push(e.value))}return{checked_values:b,unchecked_values:c}};var o5=function(){m.Ma.call(this,"www/feed",["www/common"],["feed","index"],Yaa,Zaa)};
var Yaa=function(){m.Pn.getInstance().Ed();m.By.getInstance().Ed();Naa();var a=m.zz=(0,m.C)("feed");p5.push((0,m.fg)(a,"click",waa,"feed-load-more"));p5.push((0,m.fg)(a,"click",vaa,"feed-item-expander-button"));p5.push((0,m.fg)(a,"click",uaa,"feed-item-collapser-button"));q5.push((0,m.x)("page-resize",m.yz));(0,m.yz)();var b=(0,m.P)("individual-feed"),c=!1;b&&(r5=(0,m.F)(b,"feed-name"),c="user"==(0,m.F)(b,"feed-type"));if("history"==r5||"watch_later"==r5||"favorites"==r5)O4=b=r5,p4=a,G4=(0,m.C)("feed-item-select-all-checkbox"),
s4=(0,m.C)("managed-feed-success"),t4=(0,m.C)("managed-feed-error"),w4=(0,m.C)("feed-item-remove-videos"),x4=(0,m.C)("tag-menu-button"),y4=(0,m.C)("managed-toolbar-play-all-button"),E4=(0,m.C)("feed-title-count"),s5=(0,m.P)("branded-page-v2-primary-col-header-container"),v4=(0,m.P)("addto-button",s5),t5.push((0,m.R)(G4,"click",taa)),t5.push((0,m.fg)(window.document.body,"click",saa,"feed-item-selection-action")),t5.push((0,m.fg)(window.document.body,"click",raa,"feed-item-checkbox")),t5.push((0,m.R)(w4,
"click",qaa)),"watch_later"==b&&(C4=(0,m.C)("watch-later-clear-watched-button"),t5.push((0,m.R)(C4,"click",paa)),B4()),"history"==b&&(t5.push((0,m.R)((0,m.C)("watch-history-pause-button"),"click",oaa)),t5.push((0,m.R)((0,m.C)("watch-history-resume-button"),"click",naa)),t5.push((0,m.fg)(window.document.body,"click",maa,"watch-history-clear-button")));(0,m.Tt)({"feed-load-more":N4});if((0,m.t)("INIT_AUTOSHARE")){b=new m.xz((0,m.Yc)("autoshare"));b.addServiceChangedCallback(laa);var d=(0,m.C)("facebook-connect-button");
d&&b.registerConnectDialogLauncher(d,"facebook",!0);(d=(0,m.C)("twitter-connect-button"))&&b.registerConnectDialogLauncher(d,"twitter",!0);(d=(0,m.C)("orkut-connect-button"))&&b.registerConnectDialogLauncher(d,"orkut",!0);window.autoshare=b}(0,m.t)("MUSIC_PROMO_TYPE")&&(b=(0,m.C)("mep-container"),q5.push((0,m.x)("subscription-subscribe-success",kaa)),p5.push((0,m.fg)(b,"click",jaa,"mep2-dismiss-button")),p5.push((0,m.fg)(b,"click",iaa,"channel-lockup")),M4=(0,m.F)(b,"ids-for-replacement").split(","));
(0,m.Sy)(a,c);(0,m.lv)(0);(0,m.mv)();(0,m.Dy)()};var Zaa=function(){(0,m.sa)("DELAYED_EMBEDED",[]);window.masthead&&window.masthead.dispose();S4&&((0,m.S)(S4),S4=null);(0,m.S)(T4);T4=[];U4&&((0,m.S)(U4),U4=null);(0,m.S)($4);$4.length=0;Gaa();(0,m.hq)(m.Qy);J4=m.zz=null;(0,m.S)(p5);p5.length=0;(0,m.Ka)(q5);q5.length=0;if("history"==r5||"watch_later"==r5||"favorites"==r5)(0,m.S)(t5),t5=[],x4=s4=t4=G4=E4=y4=C4=w4=v4=s5=p4=null;(0,m.ty)()};
var p4,x4,s4,t4,y4,w4,v4,F4=/[^\d\.\ ]/g,G4,E4,C4,J4,M4=[],O4,q5=[],p5=[],t5=[],s5,r5;(0,m.s)(Q4,m.qa);var $aa=/^https?:\/\/(ad.doubleclick|s0.2mdn).net$/;m.f=Q4.prototype;m.f.HB=function(a){a&&a.origin&&$aa.test(a.origin)&&"creative2yt_requestClose"==a.data&&this.Ax()};m.f.Q=function(){Q4.L.Q.call(this);(0,m.S)(this.j);(0,m.S)(this.D);this.D=this.j=null};
m.f.Ax=function(){m.T.hide("ad_creative_1");(0,m.A)("ads-masthead-hide");(0,m.Oq)((0,m.C)("page"),!0);this.F&&m.T.hide("ad_creative_collapse_btn_1");m.T.show("ad_creative_expand_btn_1");(0,m.M)(this.k,"masthead-ad-expanded");R4(this.b);(0,m.Bf)("homepage_collapse_masthead_ad",void 0,void 0)};m.f.Ps=function(){m.T.show("ad_creative_expand_btn_1");(0,m.ye)((0,m.C)("premium-yva"));(0,m.ye)((0,m.C)("video-masthead"));R4(this.b)};
m.f.cK=function(){(0,m.Bd)(window.document.getElementById("premium-yva"),"premium-yva-unexpanded","premium-yva-expanded")};m.f.dK=function(){(0,m.Bd)(window.document.getElementById("premium-yva"),"premium-yva-expanded","premium-yva-unexpanded")};m.f.NJ=function(){m.T.hide("premium-yva");(0,m.M)((0,m.C)("premium-yva"),"premium-yva-unexpanded")};m.f.hK=function(){var a=m.oh.getInstance();a.set("HIDDEN_MASTHEAD_ID",!1);a.save();(0,m.Bf)("homepage_expand_masthead_ad",void 0,void 0);(0,m.xo)(window.document.location.href)};var S4;var T4=[];var U4;var V4,W4=[],X4=[];var $4=[],a5=!0;var u5,v5,d5;m.f=c5.prototype;m.f.To=!1;
m.f.Ef=function(a){var b=(0,m.F)(this.F,"hide-watch-later"),c={action_get_dropdown:"1",hide_favorites:(0,m.F)(this.F,"hide-favorites"),hide_watch_later:b},d={video_ids:this.D};this.H&&(c.feature=this.H);var e;this.k&&(e=Qaa(this));(0,m.V)("/addto_ajax",{LF:!0,format:"XML",method:"POST",W:this,ia:c,ga:d,onSuccess:function(c,d){this.ja.innerHTML=d.html_content||"";(0,m.td)(this.ja,"no-watch-later",!!b);(0,m.td)(this.ja,"ie",m.Ud);e&&Raa(this,e);this.Pc();Paa(this);this.To=!1;a&&a()}})};
m.f.Pc=function(){this.b={};this.b.list=(0,m.C)("addto-list-panel");this.b.mK=(0,m.C)("addto-list-saving-panel");this.b.Hl=(0,m.C)("addto-list-error-panel");this.b.Ze=(0,m.C)("addto-create-panel");this.j=this.b.list;(0,m.fg)(this.b.list,"click",(0,m.q)(this.FE,this),"addto-playlist-item")};
m.f.FE=function(a){a.stopPropagation();var b=a.currentTarget;(0,m.io)(m.ao.getInstance(),b);(0,m.vd)(b,"loading")||("create-playlist"==(0,m.F)(b,"list-action")?(this.To||(Uaa(this),this.To=!0),f5(this,this.b.Ze,!0)):this.k?((0,m.vd)(b,"contains-selected-videos")?(0,m.ud)(b,"to-be-removed"):(0,m.ud)(b,"to-be-added"),e5(this)):((0,m.I)(b,"loading"),a=(0,m.F)(b,"full-list-id")||"",(0,m.vd)(b,"contains-selected-videos")?Saa(this,a):(b=(0,m.F)(b,"item-name")||"",g5(this,b,a))))};
m.f.sF=function(){var a=this.J.value;this.G=!0;var b=(0,m.Tj)(this.K,"privacy");g5(this,a,null,b)};m.f.Ap=function(){(0,m.u)((0,m.q)(function(){var a=(0,m.xc)(this.J.value);a?m.T.show(this.M):m.T.hide(this.M);var b=(0,m.Tj)(this.K,"privacy");a||!b?(0,m.Mf)(this.U,!1):(0,m.Mf)(this.U,!0)},this),0)};
m.f.ZF=function(a,b){var c=this.G;this.G=!1;if(this.P=b.full_list_id||""){if("true"==b.show_private_video_warning.toLowerCase()){var d=(0,m.O)("private-video-warning",this.ja);d&&m.T.show.apply(m.T,d)}this.k&&c?this.Ef((0,m.q)(function(){var a=Vaa(this,this.P);a&&(0,m.I)(a,"to-be-added");e5(this)},this)):this.Ef()}};
m.f.YF=function(a,b){var c=b&&b.error_message;if(c){(0,m.P)("error-details",this.b.Hl).innerHTML=c;var c=(0,m.P)("show-menu-link",this.b.Hl),d=(0,m.R)(c,"click",(0,m.q)(function(a){a.preventDefault();(0,m.S)(d);this.G?f5(this,this.b.Ze,!0):f5(this,this.b.list,!0)},this));(0,m.Il)(this.b.Hl,["dismissed-panel","fade","slide"]);f5(this,this.b.Hl)}};
m.f.aG=function(){var a=(0,m.wf)("/addto_ajax",{action_redirect_to_signin_with_add:1,video_ids:this.D,next_url:window.document.location}),b=(0,m.pe)("form");b.action=a;b.method="POST";a=(0,m.pe)("input");a.type="hidden";a.name="session_token";a.value=(0,m.Yc)("addto_ajax_logged_out");b.appendChild(a);window.document.body.appendChild(b);b.submit()};(0,m.sd)(h5);m.f=h5.prototype;m.f.xf=!1;m.f.Ip=!1;
m.f.Ef=function(){var a={},b=this.b.value;(0,m.xc)(b)||(a.search=b);var b=[],c=[],b=n5("tag-video-checkbox").checked_values,c=n5("tag-playlist-checkbox").checked_values;this.xf=!0;this.Ip=!1;(0,m.V)("/labels_ajax?action_tag_menu_dropdown=1",{method:"POST",W:this,ia:a,ga:{video_ids:b,playlist_ids:c},onSuccess:function(a,b){var c=b.tag_membership;this.Bi.innerHTML=b.html_content||"";Waa(this,c);this.xf=!1;(0,m.J)(this.ja,"loading");(0,m.dm)();this.Ip&&this.Ef()},onError:function(a){this.xf=!1;(0,m.J)(this.ja,
"loading");k5(this,(0,m.Xi)(a.response))}})};
m.f.Pc=function(){(0,m.R)(this.b,"keydown",(0,m.q)(this.Eu,this));(0,m.R)(this.b,"paste",(0,m.q)(this.Eu,this));(0,m.fg)(this.ja,"click",(0,m.q)(this.xE,this),"tag-checkbox");(0,m.fg)(this.ja,"click",(0,m.q)(this.wE,this),"add-new-tag");(0,m.fg)(this.ja,"click",(0,m.q)(this.vE,this),"apply-tag-changes");this.j&&((0,m.fg)(this.j,"click",(0,m.q)(this.lp,this),"tag-video-checkbox"),(0,m.fg)(this.j,"click",(0,m.q)(this.lp,this),"tag-playlist-checkbox"));(0,m.fg)(window.document.body,"click",(0,m.q)(this.lp,
this),"tag-refresh")};m.f.Eu=function(){(0,m.u)((0,m.q)(function(){i5(this)},this),0)};m.f.xE=function(a){a=a.target;switch((0,m.F)(a,"current-tag-membership")){case "SOME":a.Jm=!1;(0,m.Fc)(a,"current-tag-membership","NONE");break;case "NONE":(0,m.Fc)(a,"current-tag-membership","ALL");break;case "ALL":"SOME"==(0,m.F)(a,"initial-tag-membership")?((0,m.gm)(a,!0),(0,m.Fc)(a,"current-tag-membership","SOME")):(0,m.Fc)(a,"current-tag-membership","NONE")}j5(this)};m.f.lp=function(){(0,m.I)(this.ja,"loading")};
m.f.wE=function(){this.k.disabled=!0;var a=this.b.value,b=n5("tag-video-checkbox").checked_values,c=n5("tag-playlist-checkbox").checked_values,a={title:a,video_ids:b,playlist_ids:c},a={method:"POST",ia:{session_token:(0,m.F)(this.ja,"ajax-token")},ga:a,onSuccess:function(a,b){m5(this,b);i5(this)},onError:function(a){k5(this,(0,m.Xi)(a.response));i5(this)},W:this};(0,m.V)("/labels_ajax?action_create_and_apply_tag=1",a)};
m.f.vE=function(){this.Hv.disabled=!0;var a=n5("tag-video-checkbox").checked_values,b=n5("tag-playlist-checkbox").checked_values,c=n5("tag-checkbox"),d=(0,m.ae)("input","tag-checkbox",void 0).length;(0,m.V)("/labels_ajax?action_update_membership=1",{W:this,method:"POST",ia:{session_token:(0,m.F)(this.ja,"ajax-token")},ga:{video_ids:a,playlist_ids:b,tags_to_add:c.checked_values,tags_to_remove:c.unchecked_values,num_tags:d},onSuccess:function(a,b){m5(this,b);i5(this)},onError:function(a){this.Hv.disabled=
!1;k5(this,(0,m.Xi)(a.response))}})};(0,m.r)("yt.flash.embed",m.Dh);(0,m.r)("yt.www.ads.pyv.pyvHomeAfcCallback",m.zy);(0,m.r)("yt.www.ads.MastheadAd",Q4);
(0,m.r)("yt.www.lists.addto.toggleMenu",function(a,b){var c=m.ao.getInstance(),d=(0,m.W)(c),e=(0,m.C)("shared-addto-menu");if(b){var g=(0,m.P)("addto-menu",e);(0,m.io)(c,a);v5=(0,m.J)(a,d);u5||(u5=g.innerHTML);c=(0,m.F)(e,"video-ids");d=(0,m.F)(a,"video-ids");d5&&(0,m.I)(e,"lightweight-panel");(0,m.vd)(a,"flip")&&(0,m.I)(e,"flip");d&&c!=d&&((0,m.Fc)(e,"video-ids",d),g.innerHTML=u5,(0,m.Hf)(a),new c5(a))}else v5&&(0,m.I)(a,d),(0,m.J)(e,"flip")});
(0,m.r)("yt.www.TagEditingMenu.toggleTagMenu",function(a,b){if(b){var c=(0,m.C)("tag-editing-menu");(0,m.vd)(c,"loading")?h5.getInstance().Ef():(h5.getInstance(),(0,m.dm)());c=(0,m.P)("yt-combobox-search-input",c);(0,m.u)((0,m.q)(c.focus,c),0)}});Q4.prototype.autoCollapsePremiumYva=Q4.prototype.NJ;Q4.prototype.collapse_ad=Q4.prototype.Ax;Q4.prototype.expand_ad=Q4.prototype.hK;Q4.prototype.userCollapsePremiumYva=Q4.prototype.Ps;Q4.prototype.userExpandPremiumYva=Q4.prototype.cK;
Q4.prototype.userUnexpandPremiumYva=Q4.prototype.dK;(0,m.s)(o5,m.Ma);o5.prototype.enable=function(){o5.L.enable.call(this);(0,m.ql)(m.wn);(0,m.ql)(m.By)};o5.prototype.disable=function(){o5.L.disable.call(this);(0,m.sl)(m.wn);(0,m.sl)(m.By)};(0,m.Na)(new o5);})(_yt_www);
